### ISSUE TITLE
Entrega do trabalho

### ISSUE THREAD

**Issue by oliveiralex** [FernandesJr/Movie-flix#1]
Olá Fernandes, tudo bem?
Me chamo Alexandre e estou corrigindo o seu trabalho.

Gostaria de confirmar com você, pois nos meus testes 3 testes falharam, que são os específicos de autorização. São eles:

1. getProfileShouldReturnSelfWhenVisitorLogged
2. getProfileShouldReturnSelfWhenMemberLogged
3. getProfileShouldReturnUnauthorizedWhenNoUserLogged

Queria saber se nos seus testes, também falharam

Ps: Ocorreu um erro no arquivo pom.xml ao importar seu trabalho.

Abraço

**Comment by gilbertoFernandesJr** [comment]
Olá Alexandre!
Aqui no meu ambiente funcionou perfeitamente.
O erro no pom.xml pode ser pelo fato de que eu uso a IDE IntelliJ, você talvez tenha aberto em outra IDE
não sei se é este o motivo do erro, mas, é uma possibilidade.

**Comment by oliveiralex** [comment]
Muito obrigado Fernandes.
Vou aprovar o trabalho então ok?

Abraço
